'use strict';

const {
	VMError
} = require('./bridge');

/**
 * Returns the cached coffee script compiler or loads it
 * if it is not found in the cache.
 *
 * @private
 * @param {Object} [options] - Optional compiler options.
 * @return {compileCallback} The coffee script compiler.
 * @throws {VMError} If the coffee-script module can't be found.
 */
function getCoffeeScriptCompiler(options) {
	let coffeeScript;
	try {
		// The warning generated by webpack can be disabled by setting:
		// ignoreWarnings[].message = /Can't resolve 'coffee-script'/

		coffeeScript = require('coffee-script');
	} catch (e) {
		throw new VMError('Coffee-Script compiler is not installed.');
	}
	// COMPAT: verify the API here rather than inside the returned callback, so an
	// incompatible install fails at `new VMScript(...)` with an actionable message
	// instead of throwing an opaque TypeError later, during compilation.
	if (typeof coffeeScript.compile !== 'function') {
		throw new VMError('The installed coffee-script does not expose a compile() function. ' +
			'Install a release that does, or pass your own transpiler as a function: ' +
			'{ compiler: (code, filename) => javaScriptSource }.');
	}
	return (code, filename) => {
		return coffeeScript.compile(code, Object.assign({header: false, bare: true}, options));
	};
}

/**
 * Returns the cached TypeScript compiler or loads it
 * if it is not found in the cache.
 *
 * @private
 * @param {Object} [options] - Optional compiler options.
 * @return {compileCallback} The TypeScript compiler.
 * @throws {VMError} If the TypeScript module can't be found.
 */
function getTypeScriptCompiler(options) {
	let typescript;
	try {
		// The warning generated by webpack can be disabled by setting:
		// ignoreWarnings[].message = /Can't resolve 'typescript'/

		typescript = require('typescript');
	} catch (e) {
		throw new VMError('TypeScript compiler is not installed.');
	}
	// COMPAT: TypeScript 7 (the Go rewrite) reduced the CommonJS entry point to
	// `{ version, versionMajorMinor }`. `transpileModule` and `ModuleKind` are gone
	// from it, and the replacement API is published under the explicitly unstable
	// `typescript/unstable/*` subpaths -- none of which offer a single-file
	// transpile equivalent, so there is nothing to fall back to. `require` still
	// SUCCEEDS on 7.x, so this cannot be detected by the catch above: without an
	// explicit check the returned callback throws
	// "Cannot read properties of undefined (reading 'CommonJS')" at compile time,
	// which reads like a vm2 bug rather than a version mismatch.
	if (typeof typescript.transpileModule !== 'function' || !typescript.ModuleKind) {
		const version = typeof typescript.version === 'string' ? typescript.version : 'unknown version';
		throw new VMError(`The installed TypeScript (${version}) does not expose the transpileModule() API ` +
			'that vm2\'s built-in TypeScript compiler uses; it was removed from the package entry point in ' +
			'TypeScript 7. Install typescript@6 or earlier, or pass your own transpiler as a function: ' +
			'{ compiler: (code, filename) => javaScriptSource }.');
	}
	return (code, filename) => {
		return typescript.transpileModule(code, {
			fileName: filename,
			compilerOptions: Object.assign({
				module: typescript.ModuleKind.CommonJS,
			}, options)
		}).outputText;
	};
}

/**
 * Remove the shebang from source code.
 *
 * @private
 * @param {string} code - Code from which to remove the shebang.
 * @return {string} code without the shebang.
 */
function removeShebang(code) {
	if (!code.startsWith('#!')) return code;
	return '//' + code.substring(2);
}


/**
 * The JavaScript compiler, just a identity function.
 *
 * @private
 * @type {compileCallback}
 * @param {string} code - The JavaScript code.
 * @param {string} filename - Filename of this script.
 * @return {string} The code.
 */
function jsCompiler(code, filename) {
	return removeShebang(code);
}

/**
 * Look up the compiler for a specific name.
 *
 * @private
 * @param {(string|compileCallback)} compiler - A compile callback or the name of the compiler.
 * @param {Object} [options] - Optional compiler options.
 * @return {compileCallback} The resolved compiler.
 * @throws {VMError} If the compiler is unknown or the coffee script module was needed and couldn't be found.
 */
function lookupCompiler(compiler, options) {
	if ('function' === typeof compiler) return compiler;
	switch (compiler) {
		case 'coffeescript':
		case 'coffee-script':
		case 'cs':
		case 'text/coffeescript':
			return getCoffeeScriptCompiler(options);
		case 'javascript':
		case 'java-script':
		case 'js':
		case 'text/javascript':
			return jsCompiler;
		case 'typescript':
		case 'type-script':
		case 'ts':
		case 'text/typescript':
			return getTypeScriptCompiler(options);
		default:
			throw new VMError(`Unsupported compiler '${compiler}'.`);
	}
}

exports.removeShebang = removeShebang;
exports.lookupCompiler = lookupCompiler;
